// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://golrfyojxlhgwcvkjanb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvbHJmeW9qeGxoZ3djdmtqYW5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Mjc0MTIsImV4cCI6MjA2MjAwMzQxMn0.L3A12N8rG0_6AslcTo21hun4Tc2w8CSN4N4swQSsH6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);